apiVersion: v1
kind: Service
metadata:
  name: mas-vendor-page
  labels:
    app: mas-vendor-page
    app.kubernetes.io/name: mas-vendor-page
    app.kubernetes.io/component: frontend
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: mas-vendor-page
  type: ClusterIP
  sessionAffinity: None

# Made with Bob
